// Copyright (C) 2026 Yota Hamada
// SPDX-License-Identifier: GPL-3.0-or-later

package llmsgen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dagucloud/dagu/internal/tools/llmsgen"
)

func TestGenerateBuildsLLMsTextFromBundledSkillSources(t *testing.T) {
	t.Parallel()

	sourceDir := writeSkillTree(t)

	content, err := llmsgen.Generate(llmsgen.Options{
		SourceDir:    sourceDir,
		SourcePrefix: "skills/dagu",
	})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	output := string(content)
	for _, want := range []string{
		"# Dagu",
		"Dagu is a self-contained workflow orchestration engine for running DAGs defined in YAML.",
		"It runs as a single binary without requiring an external database or message broker.",
		"# DAG Authoring",
		"# Actions",
		"# Remote Action Packages",
		"# Dagu CLI Reference",
		"# Context References, Scoped Values, And Step Outputs",
		"# Coding Agent Integration",
	} {
		if !strings.Contains(output, want) {
			t.Fatalf("generated output missing %q\n%s", want, output)
		}
	}

	if strings.Contains(output, "description: Writes DAGs") {
		t.Fatalf("generated output kept YAML frontmatter:\n%s", output)
	}
	for _, redundant := range []string{
		"Generated by `make llms`; do not edit directly.",
		"## Sources",
		"## `skills/dagu/SKILL.md`",
		"## `skills/dagu/references/steptypes.md`",
	} {
		if strings.Contains(output, redundant) {
			t.Fatalf("generated output contains redundant text %q\n%s", redundant, output)
		}
	}

	assertOrder(t, output,
		"Dagu is a self-contained workflow orchestration engine",
		"# DAG Authoring",
		"# Actions",
		"# Remote Action Packages",
		"# Dagu CLI Reference",
		"# Context References, Scoped Values, And Step Outputs",
		"# Coding Agent Integration",
	)
}

func TestGenerateFailsWhenRequiredReferenceIsMissing(t *testing.T) {
	t.Parallel()

	sourceDir := writeSkillTree(t)
	if err := os.Remove(filepath.Join(sourceDir, "references", "context.md")); err != nil {
		t.Fatalf("remove context reference: %v", err)
	}

	_, err := llmsgen.Generate(llmsgen.Options{
		SourceDir:    sourceDir,
		SourcePrefix: "skills/dagu",
	})
	if err == nil {
		t.Fatal("Generate() error = nil, want missing reference error")
	}
	if !strings.Contains(err.Error(), "references/context.md") {
		t.Fatalf("Generate() error = %q, want missing context reference path", err)
	}
}

func writeSkillTree(t *testing.T) string {
	t.Helper()

	sourceDir := t.TempDir()
	referencesDir := filepath.Join(sourceDir, "references")
	if err := os.MkdirAll(referencesDir, 0o755); err != nil {
		t.Fatalf("create references dir: %v", err)
	}

	files := map[string]string{
		"SKILL.md": `---
name: dagu
description: Writes DAGs
---

# DAG Authoring

Use graph DAGs.
`,
		filepath.Join("references", "steptypes.md"): `# Actions

Use built-in actions.
`,
		filepath.Join("references", "dagu-action.md"): `# Remote Action Packages

Package reusable workflows.
`,
		filepath.Join("references", "cli.md"): `# Dagu CLI Reference

Use dagu validate.
`,
		filepath.Join("references", "context.md"): `# Context References, Scoped Values, And Step Outputs

Use scoped references.
`,
		filepath.Join("references", "codingagent.md"): `# Coding Agent Integration

Use harness.run.
`,
	}

	for name, content := range files {
		path := filepath.Join(sourceDir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	return sourceDir
}

func assertOrder(t *testing.T, content string, fragments ...string) {
	t.Helper()

	offset := 0
	for _, fragment := range fragments {
		index := strings.Index(content[offset:], fragment)
		if index < 0 {
			t.Fatalf("missing %q after offset %d", fragment, offset)
		}
		offset += index + len(fragment)
	}
}
